#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# First staging deploy of Rabit on AWS Seoul (ADR-0012).
# Run from anywhere:   bash infra/aws/scripts/first-deploy.sh
# Re-running is safe: answers are remembered in ENV_FILE (public values only, no
# secrets), and every AWS/GitHub change asks before it happens.
# Reference: infra/aws/README.md, docs/plans/owner-actions.md (O-01..O-07, O-13).

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
AWS_DIR="$ROOT/infra/aws"
ENV_FILE="$AWS_DIR/environments/staging.wizard.env"
REGION="ap-northeast-2"
TOTAL_STAGES=13

# set_env_var NAME VALUE: a variable of the GitHub `staging` environment (the
# deploy workflow reads vars.* from that environment).
set_env_var() {
  local name="$1" value="$2"
  if gh variable set "$name" --env staging --body "$value" >/dev/null 2>&1; then
    printf '  %s✓ set%s staging variable %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("GitHub staging variable $name = $value")
    warn "couldn't set $name; set it later in GitHub → Settings → Environments → staging"
  fi
}

aws_() { aws --profile "$AWS_PROFILE_NAME" --region "$REGION" "$@"; }
tofu_() { (cd "$AWS_DIR" && AWS_PROFILE="$AWS_PROFILE_NAME" tofu "$@"); }
out() { tofu_ output -json "$1"; }

banner "Rabit · first staging deploy on AWS Seoul"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Tools on this machine"
say "The wizard needs the AWS CLI v2, OpenTofu ≥ 1.10, the GitHub CLI (signed in) and jq."
missing=()
for t in aws tofu gh jq; do command -v "$t" >/dev/null 2>&1 || missing+=("$t"); done
if (( ${#missing[@]} )); then
  warn "missing: ${missing[*]}"
  step "Install on macOS:  brew install awscli opentofu gh jq"
  pause "Install them, then press Enter to check again."
  for t in aws tofu gh jq; do command -v "$t" >/dev/null 2>&1 || { warn "$t still missing"; exit 1; }; done
fi
gh auth status >/dev/null 2>&1 || { step "Sign in to GitHub:  gh auth login"; pause "Done?"; }
gh auth status >/dev/null 2>&1 || { warn "gh is not signed in"; exit 1; }
say "✓ aws $(aws --version 2>&1 | cut -d' ' -f1 | cut -d/ -f2), tofu $(tofu version | head -1 | cut -d' ' -f2), gh signed in"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "AWS account and sign-in (O-01)"
say "Use an AWS account for staging (ideally an Organization with separate staging and"
say "production accounts), MFA on every root user, and sign-in through IAM Identity Center."
note "Never use root user access keys for this."
if confirm "Do you still need to create the AWS account?"; then
  open_url "https://portal.aws.amazon.com/billing/signup"
  step "Create the account, then enable MFA on the root user (Security credentials)."
  step "Enable IAM Identity Center, create your user and give it AdministratorAccess on the staging account."
  open_url "https://console.aws.amazon.com/singlesignon"
  pause "Press Enter when your Identity Center user can sign in."
fi
ask AWS_PROFILE_NAME "AWS CLI profile name for staging (e.g. rabit-staging):"
write_env AWS_PROFILE_NAME "$AWS_PROFILE_NAME"
until ACCOUNT_ID=$(aws_ sts get-caller-identity --query Account --output text 2>/dev/null); do
  warn "profile '$AWS_PROFILE_NAME' cannot sign in yet."
  step "Set it up:  aws configure sso --profile $AWS_PROFILE_NAME   (region $REGION)"
  step "Or refresh it:  aws sso login --profile $AWS_PROFILE_NAME"
  pause "Press Enter to try again."
done
say "✓ signed in to account $ACCOUNT_ID"
write_env AWS_ACCOUNT_ID "$ACCOUNT_ID"
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Domain and Route 53 hosted zone (O-02)"
say "With a domain the stack uses api., media., media-origin. and app. under it."
say "Without one (staging only), it uses CloudFront's *.cloudfront.net names; add the"
say "domain later by setting it here and re-running from stage 6 (owner-actions O-02)."
ask DOMAIN "Domain (e.g. rabit.example; '-' for none yet):"
[[ "$DOMAIN" == "-" ]] && DOMAIN=""
write_env DOMAIN "${DOMAIN:--}"
HOSTED_ZONE_ID=""
if [[ -n "$DOMAIN" ]]; then
  HOSTED_ZONE_ID=$(aws_ route53 list-hosted-zones-by-name --dns-name "$DOMAIN." \
    --query "HostedZones[?Name=='$DOMAIN.'].Id | [0]" --output text 2>/dev/null | sed 's#/hostedzone/##')
  if [[ -z "$HOSTED_ZONE_ID" || "$HOSTED_ZONE_ID" == "None" ]]; then
    warn "no hosted zone for $DOMAIN in this account"
    open_url "https://console.aws.amazon.com/route53/v2/hostedzones"
    step "Register the domain in Route 53 (Registered domains), or create a public hosted zone"
    step "for $DOMAIN and point your registrar's name servers to the zone's NS records."
    pause "Press Enter when the hosted zone exists."
    HOSTED_ZONE_ID=$(aws_ route53 list-hosted-zones-by-name --dns-name "$DOMAIN." \
      --query "HostedZones[?Name=='$DOMAIN.'].Id | [0]" --output text | sed 's#/hostedzone/##')
  fi
  say "✓ hosted zone $HOSTED_ZONE_ID"
  note "Certificates validate by DNS, so the zone must answer for $DOMAIN publicly."
else
  say "✓ no domain: CloudFront names for now"
fi
write_env HOSTED_ZONE_ID "$HOSTED_ZONE_ID"
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Names, budget and alert recipients (O-07, O-13)"
SUFFIX="${ACCOUNT_ID: -4}"
say "Bucket names are global; a short suffix from your account id keeps them unique."
ask BUCKET_PREFIX "Bucket prefix [suggested: rabit-stg-$SUFFIX]:"
BUCKET_PREFIX="${BUCKET_PREFIX:-rabit-stg-$SUFFIX}"
ask STATE_BUCKET "OpenTofu state bucket [suggested: rabit-tfstate-$SUFFIX]:"
STATE_BUCKET="${STATE_BUCKET:-rabit-tfstate-$SUFFIX}"
ask BUDGET_USD "Monthly budget in USD [300]:"
BUDGET_USD="${BUDGET_USD:-300}"
ask BUDGET_EMAILS "Budget alert addresses, comma-separated:"
ask ALERT_EMAILS "On-call alert addresses, comma-separated:"
for k in BUCKET_PREFIX STATE_BUCKET BUDGET_USD BUDGET_EMAILS ALERT_EMAILS; do write_env "$k" "${!k}"; done
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "OpenTofu state bucket (O-04)"
say "State lives in s3://$STATE_BUCKET. It holds generated secrets: only administrators may read it."
if aws_ s3api head-bucket --bucket "$STATE_BUCKET" >/dev/null 2>&1; then
  say "✓ bucket exists"
elif confirm "Create s3://$STATE_BUCKET (versioned, private, encrypted) now?"; then
  aws_ s3api create-bucket --bucket "$STATE_BUCKET" \
    --create-bucket-configuration LocationConstraint="$REGION" >/dev/null
  aws_ s3api put-bucket-versioning --bucket "$STATE_BUCKET" --versioning-configuration Status=Enabled
  aws_ s3api put-public-access-block --bucket "$STATE_BUCKET" --public-access-block-configuration \
    BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
  aws_ s3api put-bucket-encryption --bucket "$STATE_BUCKET" --server-side-encryption-configuration \
    '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
  say "✓ created"
else
  printf '  %s✗ the next stages need the state bucket%s\n' "$RED" "$RESET"; exit 1
fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Configuration files"
list() { local IFS=,; local out=() x; for x in $1; do x="${x// /}"; [[ -n "$x" ]] && out+=("\"$x\""); done; (IFS=,; printf '[%s]' "${out[*]}"); }
cat > "$AWS_DIR/environments/staging.tfvars" <<EOF
environment         = "staging"
domain              = "$DOMAIN"
hosted_zone_id      = "$HOSTED_ZONE_ID"
bucket_prefix       = "$BUCKET_PREFIX"
budget_monthly_usd  = $BUDGET_USD
budget_alert_emails = $(list "$BUDGET_EMAILS")
alert_emails        = $(list "$ALERT_EMAILS")
EOF
cat > "$AWS_DIR/environments/staging.backend.hcl" <<EOF
bucket       = "$STATE_BUCKET"
key          = "staging/terraform.tfstate"
region       = "$REGION"
encrypt      = true
use_lockfile = true
EOF
say "Wrote (both are gitignored):"
note "  infra/aws/environments/staging.tfvars"
note "  infra/aws/environments/staging.backend.hcl"
printf '\n'; sed 's/^/    /' "$AWS_DIR/environments/staging.tfvars"
pause "Check the values above, then press Enter."

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Plan the infrastructure"
say "Services start with zero tasks: no image exists until the deploy workflow builds one."
ZERO=(-var-file=environments/staging.tfvars -var api_desired_count=0 -var media_desired_count=0 -var worker_desired_count=0)
tofu_ init -input=false -backend-config=environments/staging.backend.hcl
tofu_ plan -input=false "${ZERO[@]}" -out=staging-bootstrap.plan | tail -25
note "Expected: about 150 resources to add, 0 to change, 0 to destroy."
pause

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Create the infrastructure"
warn "This creates billable resources (≈ USD 220/month at alpha size, ADR-0012)."
note "RDS and CloudFront take 15–25 minutes."
confirm "Apply the plan now?" || { warn "stopped before apply"; exit 1; }
tofu_ apply -input=false staging-bootstrap.plan
rm -f "$AWS_DIR/staging-bootstrap.plan"
say "✓ infrastructure created"
pause

# ── 9 ────────────────────────────────────────────────────────────────────
stage "GitHub staging environment (O-05)"
REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)
say "Creating the 'staging' environment in $REPO and setting its variables from tofu output."
gh api -X PUT "repos/$REPO/environments/staging" >/dev/null && say "✓ environment exists"
URLS=$(out urls); OIDC=$(out oidc); OPS=$(out ops_task)
set_env_var AWS_REGION "$REGION"
set_env_var AWS_DEPLOY_ROLE_ARN "$(out deploy_role_arn | jq -r .)"
set_env_var ECR_REPOSITORY_URL "$(out ecr_repository_url | jq -r .)"
set_env_var OPS_SUBNETS "$(jq -r '.subnets | join(",")' <<<"$OPS")"
set_env_var OPS_SECURITY_GROUP "$(jq -r '.security_groups[0]' <<<"$OPS")"
set_env_var WEB_BUCKET "$(out web_bucket | jq -r .)"
set_env_var WEB_DISTRIBUTION_ID "$(out web_distribution_id | jq -r .)"
set_env_var API_BASE_URL "$(jq -r .api <<<"$URLS")"
set_env_var APP_URL "$(jq -r .app <<<"$URLS")"
set_env_var MEDIA_URL "$(jq -r .media <<<"$URLS")"
set_env_var MEDIA_ORIGIN_URL "$(out media_origin_url | jq -r .)"
for k in OIDC_ISSUER OIDC_CLIENT_ID OIDC_OPERATOR_ISSUER OIDC_OPERATOR_CLIENT_ID; do
  set_env_var "$k" "$(jq -r ".$k" <<<"$OIDC")"
done
pause

# ── 10 ───────────────────────────────────────────────────────────────────
stage "First deploy"
say "The deploy workflow builds the ARM64 image, runs migrations, rolls out the services,"
say "publishes the web client and ends with the post-deploy checks."
confirm "Start the deploy workflow for staging now?" || { warn "stopped before deploy"; exit 1; }
gh workflow run deploy.yml --ref main -f environment=staging
sleep 8
RUN_ID=$(gh run list --workflow deploy.yml --limit 1 --json databaseId -q '.[0].databaseId')
say "run $RUN_ID: following it (about 15 minutes)…"
gh run watch "$RUN_ID" --exit-status || { warn "the deploy failed: gh run view $RUN_ID --log-failed"; exit 1; }
say "✓ deployed"
pause

# ── 11 ───────────────────────────────────────────────────────────────────
stage "Start the services"
say "Now that an image exists, apply again with the normal task counts."
tofu_ plan -input=false -var-file=environments/staging.tfvars -out=staging.plan | tail -8
confirm "Apply?" || { warn "services still at zero tasks"; exit 1; }
tofu_ apply -input=false staging.plan
rm -f "$AWS_DIR/staging.plan"
note "Note: ECS keeps the task definitions the deploy registered (ignore_changes)."
pause

# ── 12 ───────────────────────────────────────────────────────────────────
stage "First operator (O-03)"
say "Operators cannot sign up: create the first one in the MFA operator pool."
ask OPERATOR_EMAIL "Operator's email:"
write_env OPERATOR_EMAIL "$OPERATOR_EMAIL"
POOL=$(out operator_pool_id | jq -r .)
if confirm "Create operator $OPERATOR_EMAIL in pool $POOL?"; then
  if aws_ cognito-idp admin-create-user --user-pool-id "$POOL" --username "$OPERATOR_EMAIL" \
    --user-attributes Name=email,Value="$OPERATOR_EMAIL" Name=email_verified,Value=true >/dev/null; then
    say "✓ created; Cognito emails a temporary password"
  else
    warn "not created (it may already exist)"
  fi
fi
open_url "$(jq -r .app <<<"$URLS")"
step "Sign in with '운영자 로그인 (MFA)', set a new password and register an authenticator app."
pause "Press Enter when the operator console (Ops) opens."

# ── 13 ───────────────────────────────────────────────────────────────────
stage "Alert subscriptions (O-13)"
TOPIC=$(out alerts_topic_arn | jq -r .)
say "Each alert address got an 'AWS Notification - Subscription Confirmation' email."
step "Open it and click 'Confirm subscription'. Until then, alerts reach nobody."
pause "Press Enter after confirming."
PENDING=$(aws_ sns list-subscriptions-by-topic --topic-arn "$TOPIC" \
  --query "length(Subscriptions[?SubscriptionArn=='PendingConfirmation'])" --output text)
if [[ "$PENDING" != "0" ]]; then
  SKIPPED+=("$PENDING alert subscription(s) still unconfirmed (topic $TOPIC)")
  warn "$PENDING subscription(s) still pending"
else
  say "✓ all alert subscriptions confirmed"
fi
pause

finish
say "Staging is up: $(jq -r .app <<<"$URLS")"
say "Next: restore drill and game day on staging (infra/aws/README.md → Operations)."
